# Generated by Django 5.0.6 on 2024-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_orderbook_asks_remove_orderbook_bids_asks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('duration', models.IntegerField(default=None)),
                ('price', models.FloatField(default=None)),
            ],
        ),
    ]
