# Generated by Django 5.0.6 on 2024-06-17 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_averageprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='averageprice',
            name='timestamp_lower',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averageprice',
            name='timestamp_upper',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
